name: Build PS3 Launcher

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: dpenendecies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            wget \
            curl \
            unzip \
            make \
            gcc \
            g++ \
            python3

      - name: Install PSL1GHT SDK
        run: |
          curl -fsSL https://miskaa.pl/legacysdk/sh/setup.sh | sudo bash

      - name: setup environment
        shell: bash
        run: |
          source ~/.bashrc

      - name: build ps3soundlib
        shell: bash
        run: |
          source ~/.bashrc
          git clone https://github.com/wargio/ps3soundlib
          cd ps3soundlib
          make

      - name: build tiny3D
        shell: bash
        run: |
          source ~/.bashrc
          git clone https://github.com/wargio/tiny3D.git
          cd tiny3D
          make

      - name: build
        shell: bash
        run: |
          source ~/.bashrc
          make clean
          make

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: ps3-launcher
          path: |
            *.elf
            *.self
            *.fake.self
